services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    healthcheck:
      disable: true
    volumes:
      - "$DIR_CONFIG/sonarr/config:/config"
      - "$DIR_DATA:/data"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.routers.sonarr.rule=Host(`sonarr.$HOSTNAME`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://sonarr.$HOSTNAME
      - homepage.description=Series Management
      - homepage.weight=2
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=$API_KEY_SONARR
