networks:
  traefik:
    name: traefik
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.0.0/16
          ip_range: 10.11.0.0/24
          gateway: 10.11.0.1
  socket-proxy:
    name: socket-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          ip_range: 10.10.0.0/24
          gateway: 10.10.0.1

include:
  - path: socketproxy/docker-compose.yml
  - path: traefik/docker-compose.yml
  - path: adguardhome/docker-compose.yml
  - path: qbittorrent/docker-compose.yml
  - path: flaresolverr/docker-compose.yml
  - path: prowlarr/docker-compose.yml
  - path: sonarr/docker-compose.yml
  - path: radarr/docker-compose.yml
  - path: recyclarr/docker-compose.yml
  - path: unpackerr/docker-compose.yml
  - path: bazarr/docker-compose.yml
  - path: jellyfin/docker-compose.yml
  - path: jellyseerr/docker-compose.yml
  - path: homepage/docker-compose.yml
  - path: watchtower/docker-compose.yml
  - path: portainer/docker-compose.yml
