services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    healthcheck:
      disable: true
    volumes:
      - "$DIR_CONFIG/readarr/config:/config"
      - "$DIR_DATA:/data"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.readarr.service=readarr
      - traefik.http.routers.readarr.rule=Host(`readarr.$HOSTNAME`)
      - traefik.http.services.readarr.loadbalancer.server.port=8787

      - homepage.group=Reading
      - homepage.name=Readarr
      - homepage.icon=readarr.png
      - homepage.href=http://readarr.$HOSTNAME
      - homepage.description=eBooks Management
      - homepage.weight=0
      - homepage.widget.type=readarr
      - homepage.widget.url=http://readarr:8787
      - homepage.widget.key=$API_KEY_READARR
