services:
  unpackerr:
    image: ghcr.io/hotio/unpackerr:latest
    container_name: unpackerr
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    healthcheck:
      disable: true
    volumes:
      - "$DIR_CONFIG/unpackerr/config:/config"
      - "$DIR_DATA:/data"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=$API_KEY_SONARR
      - UN_SONARR_0_PATHS_0=/data/downloads
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=$API_KEY_RADARR
      - UN_RADARR_0_PATHS=/data/downloads
