services:
  calibreweb:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibreweb
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    healthcheck:
      disable: true
    volumes:
      - "$DIR_CONFIG/calibreweb/config:/config"
      - "$DIR_DATA/media/books:/books"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibreweb.service=calibreweb
      - traefik.http.routers.calibreweb.rule=Host(`calibreweb.$HOSTNAME`, `cw.$HOSTNAME`)
      - traefik.http.services.calibreweb.loadbalancer.server.port=8083

      - homepage.group=Reading
      - homepage.name=Calibre Web
      - homepage.icon=calibre.png
      - homepage.href=http://calibreweb.$HOSTNAME
      - homepage.description=eBooks Library
      - homepage.weight=1
