services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    healthcheck:
      disable: true
    volumes:
      - "$DIR_CONFIG/radarr/config:/config"
      - "$DIR_DATA:/data"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.routers.radarr.rule=Host(`radarr.$HOSTNAME`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878

      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://radarr.$HOSTNAME
      - homepage.description=Movies Management
      - homepage.weight=3
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=$API_KEY_RADARR
