services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    healthcheck:
      disable: true
    volumes:
      - "$DIR_CONFIG/calibre/config:/config"
      - "$DIR_DATA/media/books:/data/media/books"
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.service=calibre
      - traefik.http.routers.calibre.rule=Host(`calibre.$HOSTNAME`)
      - traefik.http.services.calibre.loadbalancer.server.port=8080

      - homepage.group=Reading
      - homepage.name=Calibre
      - homepage.icon=calibre.png
      - homepage.href=http://calibre.$HOSTNAME
      - homepage.description=eBooks Server
      - homepage.weight=1
