services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
        ipv4_address: 10.11.0.111
    ports:
        # DNS
        - 53:53/tcp
        - 53:53/udp
        # Setup
        #- 3000:3000
    volumes:
      - "$DIR_CONFIG/adguardhome/config:/opt/adguardhome/conf"
      - "$DIR_CONFIG/adguardhome/work:/opt/adguardhome/work"
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguardhome.service=adguardhome
      - traefik.http.routers.adguardhome.rule=Host(`adguardhome.$HOSTNAME`)
      - traefik.http.services.adguardhome.loadbalancer.server.port=80

      - homepage.group=Tools
      - homepage.name=Adguard Home
      - homepage.icon=adguard-home.png
      - homepage.href=http://adguardhome.$HOSTNAME
      - homepage.description=DNS Management
      - homepage.weight=0
