services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    ports:
      - "7359:7359/udp"
      - "1900:1900/udp"
    healthcheck:
      disable: true
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "$DIR_CONFIG/jellyfin/config:/config"
      - "$DIR_CONFIG/jellyfin/cache:/cache"
      - "$DIR_DATA/media:/data"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=jellyfin.$HOSTNAME
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.$HOSTNAME`, `fin.$HOSTNAME`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://jellyfin.$HOSTNAME
      - homepage.description=Media Server
      - homepage.weight=0
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:8096
      - homepage.widget.key=$API_KEY_JELLYFIN
