services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ