services:
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: jellyseerr
    restart: $DEFAULT_RESTART
    networks:
      traefik:
        priority: 20
    healthcheck:
      disable: true
    volumes:
      - "$DIR_CONFIG/jellyseerr/config:/config"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.service=jellyseerr
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.$HOSTNAME`, `seerr.$HOSTNAME`)
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055

      - homepage.group=Media
      - homepage.name=Jellyseerr
      - homepage.icon=jellyseerr.png
      - homepage.href=http://jellyseerr.$HOSTNAME
      - homepage.description=Content Recommendations and Request Management
      - homepage.weight=1
      - homepage.widget.type=jellyseerr
      - homepage.widget.url=http://jellyseerr:5055
      - homepage.widget.key=$API_KEY_JELLYSEER
